### PR TITLE
Add Systemli and it's services

### PR DESCRIPTION
**Pull request by t2d**
I created this PR after the example of Riseup. Please let me know, if you prefer a different structure.

### CODE REVIEW

**Comment by alecmuffett** [comment]
why are these not all on a single onion address with subdomains?

**Comment by t2d** [comment]
I thought this is not possible for other services than http? If it is possible, can you please point me to the necessary doc?

**Comment by alecmuffett** [comment]
there is no necessary doc.  they will all just work if the requests are routed by a reverse proxy at the server end.

**Comment by alecmuffett** [comment]
done using new system

**Pull request closed without merging**
